module.exports = [
  {
    id: 1,
    picture: "http://www.beautifullife.info/wp-content/uploads/2017/07/26/bugatti_chiron_2018.jpg",
    name: "Bugatti Chiron",
    make: "Bugatti",
    model: "Chiron",
    year: 2018,
  },
  {
    id: 2,
    picture: "http://www.beautifullife.info/wp-content/uploads/2017/07/26/pagani_huayra_bc.jpg",
    name: "Pagani Huayra BC",
    make: "Pagani",
    model: "Huayra BC",
    year: 2016,
  },
  {
    id: 3,
    picture: "http://www.beautifullife.info/wp-content/uploads/2017/07/26/most_expensive_ferrari.jpg",
    name: "Ferrari Pininfarina Sergio",
    make: "Ferrari",
    model: "Pininfarina Sergio",
    year: 2015,
  },
  {
    id: 4,
    picture: "http://www.beautifullife.info/wp-content/uploads/2017/07/26/aston_martin_valkyrie.jpg",
    name: "Aston Martin Valkyrie",
    make: "Aston Martin",
    model: "Valkyrie",
    year: 2016,
  },
  {
    id: 5,
    picture: "http://www.beautifullife.info/wp-content/uploads/2017/07/26/limited_edition_bugatti_veyron_by_mansory_vivere.jpg",
    name: "Limited Edition Bugatti Veyron Read",
    make: "Bugatti",
    model: "Limited Edition Veyron",
    year: 2009,
  },
  {
    id: 6,
    picture: "http://www.beautifullife.info/wp-content/uploads/2017/07/26/lykan_hypersport.jpg",
    name: "Lykan Hypersport",
    make: "Lykan",
    model: "Hypersport",
    year: 2011,
  },
  {
    id: 7,
    picture: "http://www.beautifullife.info/wp-content/uploads/2017/07/26/mclaren_p1_lm_big_photos.jpg",
    name: "McLaren P1 LM",
    make: "McLaren",
    model: "P1 LM",
    year: 2009,
  },
  {
    id: 8,
    picture: "http://www.beautifullife.info/wp-content/uploads/2017/07/26/super_car_most_expensive_in_the_world.jpg",
    name: "Lamborghini Veneno Roadster",
    make: "Lamborghini",
    model: "Veneno Roadster",
    year: 2011,
  },
  {
    id: 9,
    img: "http://www.beautifullife.info/wp-content/uploads/2017/07/26/super_car_most_expensive_in_the_world.jpg",
    name: "Koenigsegg CCXR Trevita",
    make: "Koenigsegg",
    model: "CCXR Trevita",
    year: 2015,
  },
  {
    id: 10,
    picture: "http://www.beautifullife.info/wp-content/uploads/2017/07/26/worlds_most_expensive_car.jpg",
    name: "Rolls Royce Sweptail",
    make: "Rolls Royce",
    model: "Sweptail",
    year: 2014,
  },
];